---
# file: #roles/common/tasks/main.yml

- name: SYSTEM / amazon
  import_tasks: amazon.yml
  when: ansible_distribution == "Amazon"

- name: SYSTEM / ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
